//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Skinz\Desktop\Harmony\Harmony.Antlr\HarmonyParser.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IHarmonyParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public partial class HarmonyParserBaseListener : IHarmonyParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompilationUnit([NotNull] HarmonyParser.CompilationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompilationUnit([NotNull] HarmonyParser.CompilationUnitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.attributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributes([NotNull] HarmonyParser.AttributesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.attributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributes([NotNull] HarmonyParser.AttributesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.unitDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitDeclaration([NotNull] HarmonyParser.UnitDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.unitDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitDeclaration([NotNull] HarmonyParser.UnitDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] HarmonyParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] HarmonyParser.BlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockStatement([NotNull] HarmonyParser.BlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockStatement([NotNull] HarmonyParser.BlockStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] HarmonyParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] HarmonyParser.StatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.unitStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitStatement([NotNull] HarmonyParser.UnitStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.unitStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitStatement([NotNull] HarmonyParser.UnitStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.noteStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoteStatement([NotNull] HarmonyParser.NoteStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.noteStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoteStatement([NotNull] HarmonyParser.NoteStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.chordStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChordStatement([NotNull] HarmonyParser.ChordStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.chordStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChordStatement([NotNull] HarmonyParser.ChordStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.stepStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStepStatement([NotNull] HarmonyParser.StepStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.stepStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStepStatement([NotNull] HarmonyParser.StepStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.blockFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockFunction([NotNull] HarmonyParser.BlockFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.blockFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockFunction([NotNull] HarmonyParser.BlockFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] HarmonyParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] HarmonyParser.FunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.propagateFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropagateFunction([NotNull] HarmonyParser.PropagateFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.propagateFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropagateFunction([NotNull] HarmonyParser.PropagateFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.transposeFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransposeFunction([NotNull] HarmonyParser.TransposeFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.transposeFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransposeFunction([NotNull] HarmonyParser.TransposeFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.strumFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrumFunction([NotNull] HarmonyParser.StrumFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.strumFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrumFunction([NotNull] HarmonyParser.StrumFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.timesFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTimesFunction([NotNull] HarmonyParser.TimesFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.timesFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTimesFunction([NotNull] HarmonyParser.TimesFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.bassFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBassFunction([NotNull] HarmonyParser.BassFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.bassFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBassFunction([NotNull] HarmonyParser.BassFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.addFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddFunction([NotNull] HarmonyParser.AddFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.addFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddFunction([NotNull] HarmonyParser.AddFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.noteLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoteLiteral([NotNull] HarmonyParser.NoteLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.noteLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoteLiteral([NotNull] HarmonyParser.NoteLiteralContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.chordLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChordLiteral([NotNull] HarmonyParser.ChordLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.chordLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChordLiteral([NotNull] HarmonyParser.ChordLiteralContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HarmonyParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] HarmonyParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HarmonyParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] HarmonyParser.NumberContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
