//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Skinz\Desktop\Harmony\Harmony.Antlr\HarmonyParser.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using System.Collections.Generic;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public partial class HarmonyParser : Parser {
	public const int
		UNIT=1, ATR_NAME=2, ATR_TEMPO=3, ATR_AUTHOR=4, NOTE=5, CHORD=6, STEP=7, 
		NOTES=8, PEDAL=9, TRANSPOSE=10, PROPAGATE=11, STRUM=12, ARPEGGIO=13, TIMES=14, 
		BASS=15, ADD=16, ON=17, OFF=18, LPAREN=19, RPAREN=20, LBRACE=21, RBRACE=22, 
		COMMA=23, DOT=24, SEMI=25, COLON=26, SHARP=27, LBRACKET=28, RBRACKET=29, 
		COMMENT=30, LINE_COMMENT=31, IDENTIFIER=32, WS=33, DECIMAL_LITERAL=34, 
		FLOAT_LITERAL=35;
	public const int
		RULE_compilationUnit = 0, RULE_attributes = 1, RULE_unitDeclaration = 2, 
		RULE_block = 3, RULE_blockStatement = 4, RULE_statement = 5, RULE_unitStatement = 6, 
		RULE_noteStatement = 7, RULE_chordStatement = 8, RULE_stepStatement = 9, 
		RULE_notesStatement = 10, RULE_pedalStatement = 11, RULE_blockFunction = 12, 
		RULE_function = 13, RULE_propagateFunction = 14, RULE_transposeFunction = 15, 
		RULE_arpeggioFunction = 16, RULE_strumFunction = 17, RULE_timesFunction = 18, 
		RULE_bassFunction = 19, RULE_addFunction = 20, RULE_noteLiteral = 21, 
		RULE_chordLiteral = 22, RULE_number = 23;
	public static readonly string[] ruleNames = {
		"compilationUnit", "attributes", "unitDeclaration", "block", "blockStatement", 
		"statement", "unitStatement", "noteStatement", "chordStatement", "stepStatement", 
		"notesStatement", "pedalStatement", "blockFunction", "function", "propagateFunction", 
		"transposeFunction", "arpeggioFunction", "strumFunction", "timesFunction", 
		"bassFunction", "addFunction", "noteLiteral", "chordLiteral", "number"
	};

	private static readonly string[] _LiteralNames = {
		null, "'unit'", "'name'", "'tempo'", "'author'", "'note'", "'chord'", 
		"'step'", "'notes'", "'pedal'", "'transpose'", "'propagate'", "'strum'", 
		"'arpeggio'", "'times'", "'bass'", "'add'", "'on'", "'off'", "'('", "')'", 
		"'{'", "'}'", "','", "'.'", "';'", "':'", "'#'", "'['", "']'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "UNIT", "ATR_NAME", "ATR_TEMPO", "ATR_AUTHOR", "NOTE", "CHORD", 
		"STEP", "NOTES", "PEDAL", "TRANSPOSE", "PROPAGATE", "STRUM", "ARPEGGIO", 
		"TIMES", "BASS", "ADD", "ON", "OFF", "LPAREN", "RPAREN", "LBRACE", "RBRACE", 
		"COMMA", "DOT", "SEMI", "COLON", "SHARP", "LBRACKET", "RBRACKET", "COMMENT", 
		"LINE_COMMENT", "IDENTIFIER", "WS", "DECIMAL_LITERAL", "FLOAT_LITERAL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[System.Obsolete("Use Vocabulary instead.")]
	public static readonly string[] tokenNames = GenerateTokenNames(DefaultVocabulary, _SymbolicNames.Length);

	private static string[] GenerateTokenNames(IVocabulary vocabulary, int length) {
		string[] tokenNames = new string[length];
		for (int i = 0; i < tokenNames.Length; i++) {
			tokenNames[i] = vocabulary.GetLiteralName(i);
			if (tokenNames[i] == null) {
				tokenNames[i] = vocabulary.GetSymbolicName(i);
			}

			if (tokenNames[i] == null) {
				tokenNames[i] = "<INVALID>";
			}
		}

		return tokenNames;
	}

	[System.Obsolete("Use IRecognizer.Vocabulary instead.")]
	public override string[] TokenNames
	{
		get
		{
			return tokenNames;
		}
	}

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "HarmonyParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public HarmonyParser(ITokenStream input)
		: base(input)
	{
		_interp = new ParserATNSimulator(this,_ATN);
	}
	public partial class CompilationUnitContext : ParserRuleContext {
		public AttributesContext attributes() {
			return GetRuleContext<AttributesContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(HarmonyParser.Eof, 0); }
		public UnitDeclarationContext[] unitDeclaration() {
			return GetRuleContexts<UnitDeclarationContext>();
		}
		public UnitDeclarationContext unitDeclaration(int i) {
			return GetRuleContext<UnitDeclarationContext>(i);
		}
		public CompilationUnitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compilationUnit; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterCompilationUnit(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitCompilationUnit(this);
		}
	}

	[RuleVersion(0)]
	public CompilationUnitContext compilationUnit() {
		CompilationUnitContext _localctx = new CompilationUnitContext(_ctx, State);
		EnterRule(_localctx, 0, RULE_compilationUnit);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 48; attributes();
			State = 52;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while (_la==UNIT) {
				{
				{
				State = 49; unitDeclaration();
				}
				}
				State = 54;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			State = 55; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttributesContext : ParserRuleContext {
		public IToken name;
		public IToken author;
		public IToken tempo;
		public ITerminalNode[] IDENTIFIER() { return GetTokens(HarmonyParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(HarmonyParser.IDENTIFIER, i);
		}
		public ITerminalNode DECIMAL_LITERAL() { return GetToken(HarmonyParser.DECIMAL_LITERAL, 0); }
		public AttributesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attributes; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterAttributes(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitAttributes(this);
		}
	}

	[RuleVersion(0)]
	public AttributesContext attributes() {
		AttributesContext _localctx = new AttributesContext(_ctx, State);
		EnterRule(_localctx, 2, RULE_attributes);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 57; Match(ATR_NAME);
			State = 58; Match(COLON);
			State = 59; _localctx.name = Match(IDENTIFIER);
			}
			{
			State = 61; Match(ATR_AUTHOR);
			State = 62; Match(COLON);
			State = 63; _localctx.author = Match(IDENTIFIER);
			}
			{
			State = 65; Match(ATR_TEMPO);
			State = 66; Match(COLON);
			State = 67; _localctx.tempo = Match(DECIMAL_LITERAL);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnitDeclarationContext : ParserRuleContext {
		public IToken name;
		public ITerminalNode UNIT() { return GetToken(HarmonyParser.UNIT, 0); }
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public ITerminalNode IDENTIFIER() { return GetToken(HarmonyParser.IDENTIFIER, 0); }
		public UnitDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unitDeclaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterUnitDeclaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitUnitDeclaration(this);
		}
	}

	[RuleVersion(0)]
	public UnitDeclarationContext unitDeclaration() {
		UnitDeclarationContext _localctx = new UnitDeclarationContext(_ctx, State);
		EnterRule(_localctx, 4, RULE_unitDeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 69; Match(UNIT);
			State = 70; _localctx.name = Match(IDENTIFIER);
			State = 71; block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public BlockStatementContext[] blockStatement() {
			return GetRuleContexts<BlockStatementContext>();
		}
		public BlockStatementContext blockStatement(int i) {
			return GetRuleContext<BlockStatementContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(_ctx, State);
		EnterRule(_localctx, 6, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 73; Match(LBRACE);
			State = 77;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NOTE) | (1L << CHORD) | (1L << STEP) | (1L << NOTES) | (1L << PEDAL) | (1L << IDENTIFIER))) != 0)) {
				{
				{
				State = 74; blockStatement();
				}
				}
				State = 79;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			State = 80; Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockStatementContext : ParserRuleContext {
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public ITerminalNode DOT() { return GetToken(HarmonyParser.DOT, 0); }
		public BlockFunctionContext blockFunction() {
			return GetRuleContext<BlockFunctionContext>(0);
		}
		public BlockStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_blockStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterBlockStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitBlockStatement(this);
		}
	}

	[RuleVersion(0)]
	public BlockStatementContext blockStatement() {
		BlockStatementContext _localctx = new BlockStatementContext(_ctx, State);
		EnterRule(_localctx, 8, RULE_blockStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 82; statement();
			State = 85;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,2,_ctx) ) {
			case 1:
				{
				State = 83; Match(DOT);
				State = 84; blockFunction();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public StepStatementContext stepStatement() {
			return GetRuleContext<StepStatementContext>(0);
		}
		public NoteStatementContext noteStatement() {
			return GetRuleContext<NoteStatementContext>(0);
		}
		public ChordStatementContext chordStatement() {
			return GetRuleContext<ChordStatementContext>(0);
		}
		public UnitStatementContext unitStatement() {
			return GetRuleContext<UnitStatementContext>(0);
		}
		public NotesStatementContext notesStatement() {
			return GetRuleContext<NotesStatementContext>(0);
		}
		public PedalStatementContext pedalStatement() {
			return GetRuleContext<PedalStatementContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(_ctx, State);
		EnterRule(_localctx, 10, RULE_statement);
		try {
			State = 93;
			_errHandler.Sync(this);
			switch (_input.La(1)) {
			case STEP:
				EnterOuterAlt(_localctx, 1);
				{
				State = 87; stepStatement();
				}
				break;
			case NOTE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 88; noteStatement();
				}
				break;
			case CHORD:
				EnterOuterAlt(_localctx, 3);
				{
				State = 89; chordStatement();
				}
				break;
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 4);
				{
				State = 90; unitStatement();
				}
				break;
			case NOTES:
				EnterOuterAlt(_localctx, 5);
				{
				State = 91; notesStatement();
				}
				break;
			case PEDAL:
				EnterOuterAlt(_localctx, 6);
				{
				State = 92; pedalStatement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnitStatementContext : ParserRuleContext {
		public IToken name;
		public ITerminalNode IDENTIFIER() { return GetToken(HarmonyParser.IDENTIFIER, 0); }
		public UnitStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unitStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterUnitStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitUnitStatement(this);
		}
	}

	[RuleVersion(0)]
	public UnitStatementContext unitStatement() {
		UnitStatementContext _localctx = new UnitStatementContext(_ctx, State);
		EnterRule(_localctx, 12, RULE_unitStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 95; _localctx.name = Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NoteStatementContext : ParserRuleContext {
		public NumberContext duration;
		public NumberContext velocity;
		public ITerminalNode NOTE() { return GetToken(HarmonyParser.NOTE, 0); }
		public NoteLiteralContext noteLiteral() {
			return GetRuleContext<NoteLiteralContext>(0);
		}
		public NumberContext[] number() {
			return GetRuleContexts<NumberContext>();
		}
		public NumberContext number(int i) {
			return GetRuleContext<NumberContext>(i);
		}
		public NoteStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_noteStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterNoteStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitNoteStatement(this);
		}
	}

	[RuleVersion(0)]
	public NoteStatementContext noteStatement() {
		NoteStatementContext _localctx = new NoteStatementContext(_ctx, State);
		EnterRule(_localctx, 14, RULE_noteStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 97; Match(NOTE);
			State = 98; noteLiteral();
			State = 99; Match(LPAREN);
			State = 100; _localctx.duration = number();
			State = 101; Match(COMMA);
			State = 102; _localctx.velocity = number();
			State = 103; Match(RPAREN);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ChordStatementContext : ParserRuleContext {
		public NumberContext duration;
		public NumberContext velocity;
		public IToken octave;
		public ITerminalNode CHORD() { return GetToken(HarmonyParser.CHORD, 0); }
		public ChordLiteralContext chordLiteral() {
			return GetRuleContext<ChordLiteralContext>(0);
		}
		public NumberContext[] number() {
			return GetRuleContexts<NumberContext>();
		}
		public NumberContext number(int i) {
			return GetRuleContext<NumberContext>(i);
		}
		public ITerminalNode DECIMAL_LITERAL() { return GetToken(HarmonyParser.DECIMAL_LITERAL, 0); }
		public ChordStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_chordStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterChordStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitChordStatement(this);
		}
	}

	[RuleVersion(0)]
	public ChordStatementContext chordStatement() {
		ChordStatementContext _localctx = new ChordStatementContext(_ctx, State);
		EnterRule(_localctx, 16, RULE_chordStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 105; Match(CHORD);
			State = 106; chordLiteral();
			State = 107; Match(LPAREN);
			State = 108; _localctx.duration = number();
			State = 109; Match(COMMA);
			State = 110; _localctx.velocity = number();
			State = 111; Match(COMMA);
			State = 112; _localctx.octave = Match(DECIMAL_LITERAL);
			State = 113; Match(RPAREN);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StepStatementContext : ParserRuleContext {
		public BlockStatementContext target;
		public NumberContext duration;
		public ITerminalNode STEP() { return GetToken(HarmonyParser.STEP, 0); }
		public BlockStatementContext blockStatement() {
			return GetRuleContext<BlockStatementContext>(0);
		}
		public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public StepStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stepStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterStepStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitStepStatement(this);
		}
	}

	[RuleVersion(0)]
	public StepStatementContext stepStatement() {
		StepStatementContext _localctx = new StepStatementContext(_ctx, State);
		EnterRule(_localctx, 18, RULE_stepStatement);
		try {
			State = 119;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,4,_ctx) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 115; Match(STEP);
				State = 116; _localctx.target = blockStatement();
				}
				}
				break;

			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				{
				State = 117; Match(STEP);
				State = 118; _localctx.duration = number();
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NotesStatementContext : ParserRuleContext {
		public NoteLiteralContext note;
		public NoteLiteralContext lastNote;
		public NumberContext duration;
		public NumberContext velocity;
		public ITerminalNode NOTES() { return GetToken(HarmonyParser.NOTES, 0); }
		public NoteLiteralContext[] noteLiteral() {
			return GetRuleContexts<NoteLiteralContext>();
		}
		public NoteLiteralContext noteLiteral(int i) {
			return GetRuleContext<NoteLiteralContext>(i);
		}
		public NumberContext[] number() {
			return GetRuleContexts<NumberContext>();
		}
		public NumberContext number(int i) {
			return GetRuleContext<NumberContext>(i);
		}
		public NotesStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_notesStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterNotesStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitNotesStatement(this);
		}
	}

	[RuleVersion(0)]
	public NotesStatementContext notesStatement() {
		NotesStatementContext _localctx = new NotesStatementContext(_ctx, State);
		EnterRule(_localctx, 20, RULE_notesStatement);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 121; Match(NOTES);
			State = 127;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,5,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					{
					{
					State = 122; _localctx.note = noteLiteral();
					State = 123; Match(COMMA);
					}
					} 
				}
				State = 129;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,5,_ctx);
			}
			State = 130; _localctx.lastNote = noteLiteral();
			State = 131; Match(LPAREN);
			State = 132; _localctx.duration = number();
			State = 133; Match(COMMA);
			State = 134; _localctx.velocity = number();
			State = 135; Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PedalStatementContext : ParserRuleContext {
		public ITerminalNode PEDAL() { return GetToken(HarmonyParser.PEDAL, 0); }
		public ITerminalNode ON() { return GetToken(HarmonyParser.ON, 0); }
		public ITerminalNode OFF() { return GetToken(HarmonyParser.OFF, 0); }
		public PedalStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pedalStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterPedalStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitPedalStatement(this);
		}
	}

	[RuleVersion(0)]
	public PedalStatementContext pedalStatement() {
		PedalStatementContext _localctx = new PedalStatementContext(_ctx, State);
		EnterRule(_localctx, 22, RULE_pedalStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 137; Match(PEDAL);
			State = 138;
			_la = _input.La(1);
			if ( !(_la==ON || _la==OFF) ) {
			_errHandler.RecoverInline(this);
			} else {
				if (_input.La(1) == TokenConstants.Eof) {
					matchedEOF = true;
				}

				_errHandler.ReportMatch(this);
				Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockFunctionContext : ParserRuleContext {
		public FunctionContext current;
		public BlockFunctionContext next;
		public FunctionContext function() {
			return GetRuleContext<FunctionContext>(0);
		}
		public ITerminalNode DOT() { return GetToken(HarmonyParser.DOT, 0); }
		public BlockFunctionContext blockFunction() {
			return GetRuleContext<BlockFunctionContext>(0);
		}
		public BlockFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_blockFunction; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterBlockFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitBlockFunction(this);
		}
	}

	[RuleVersion(0)]
	public BlockFunctionContext blockFunction() {
		BlockFunctionContext _localctx = new BlockFunctionContext(_ctx, State);
		EnterRule(_localctx, 24, RULE_blockFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 140; _localctx.current = function();
			State = 143;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,6,_ctx) ) {
			case 1:
				{
				State = 141; Match(DOT);
				State = 142; _localctx.next = blockFunction();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionContext : ParserRuleContext {
		public TransposeFunctionContext transposeFunction() {
			return GetRuleContext<TransposeFunctionContext>(0);
		}
		public PropagateFunctionContext propagateFunction() {
			return GetRuleContext<PropagateFunctionContext>(0);
		}
		public ArpeggioFunctionContext arpeggioFunction() {
			return GetRuleContext<ArpeggioFunctionContext>(0);
		}
		public StrumFunctionContext strumFunction() {
			return GetRuleContext<StrumFunctionContext>(0);
		}
		public TimesFunctionContext timesFunction() {
			return GetRuleContext<TimesFunctionContext>(0);
		}
		public BassFunctionContext bassFunction() {
			return GetRuleContext<BassFunctionContext>(0);
		}
		public AddFunctionContext addFunction() {
			return GetRuleContext<AddFunctionContext>(0);
		}
		public FunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitFunction(this);
		}
	}

	[RuleVersion(0)]
	public FunctionContext function() {
		FunctionContext _localctx = new FunctionContext(_ctx, State);
		EnterRule(_localctx, 26, RULE_function);
		try {
			State = 152;
			_errHandler.Sync(this);
			switch (_input.La(1)) {
			case TRANSPOSE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 145; transposeFunction();
				}
				break;
			case PROPAGATE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 146; propagateFunction();
				}
				break;
			case ARPEGGIO:
				EnterOuterAlt(_localctx, 3);
				{
				State = 147; arpeggioFunction();
				}
				break;
			case STRUM:
				EnterOuterAlt(_localctx, 4);
				{
				State = 148; strumFunction();
				}
				break;
			case TIMES:
				EnterOuterAlt(_localctx, 5);
				{
				State = 149; timesFunction();
				}
				break;
			case BASS:
				EnterOuterAlt(_localctx, 6);
				{
				State = 150; bassFunction();
				}
				break;
			case ADD:
				EnterOuterAlt(_localctx, 7);
				{
				State = 151; addFunction();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropagateFunctionContext : ParserRuleContext {
		public IToken amount;
		public ITerminalNode PROPAGATE() { return GetToken(HarmonyParser.PROPAGATE, 0); }
		public ITerminalNode DECIMAL_LITERAL() { return GetToken(HarmonyParser.DECIMAL_LITERAL, 0); }
		public PropagateFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_propagateFunction; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterPropagateFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitPropagateFunction(this);
		}
	}

	[RuleVersion(0)]
	public PropagateFunctionContext propagateFunction() {
		PropagateFunctionContext _localctx = new PropagateFunctionContext(_ctx, State);
		EnterRule(_localctx, 28, RULE_propagateFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 154; Match(PROPAGATE);
			State = 155; Match(LPAREN);
			State = 156; _localctx.amount = Match(DECIMAL_LITERAL);
			State = 157; Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TransposeFunctionContext : ParserRuleContext {
		public IToken value;
		public ITerminalNode TRANSPOSE() { return GetToken(HarmonyParser.TRANSPOSE, 0); }
		public ITerminalNode DECIMAL_LITERAL() { return GetToken(HarmonyParser.DECIMAL_LITERAL, 0); }
		public TransposeFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_transposeFunction; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterTransposeFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitTransposeFunction(this);
		}
	}

	[RuleVersion(0)]
	public TransposeFunctionContext transposeFunction() {
		TransposeFunctionContext _localctx = new TransposeFunctionContext(_ctx, State);
		EnterRule(_localctx, 30, RULE_transposeFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 159; Match(TRANSPOSE);
			State = 160; Match(LPAREN);
			State = 161; _localctx.value = Match(DECIMAL_LITERAL);
			State = 162; Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArpeggioFunctionContext : ParserRuleContext {
		public ITerminalNode ARPEGGIO() { return GetToken(HarmonyParser.ARPEGGIO, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(HarmonyParser.IDENTIFIER, 0); }
		public ArpeggioFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arpeggioFunction; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterArpeggioFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitArpeggioFunction(this);
		}
	}

	[RuleVersion(0)]
	public ArpeggioFunctionContext arpeggioFunction() {
		ArpeggioFunctionContext _localctx = new ArpeggioFunctionContext(_ctx, State);
		EnterRule(_localctx, 32, RULE_arpeggioFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 164; Match(ARPEGGIO);
			State = 165; Match(LPAREN);
			State = 166; Match(IDENTIFIER);
			State = 167; Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StrumFunctionContext : ParserRuleContext {
		public NumberContext offset;
		public ITerminalNode STRUM() { return GetToken(HarmonyParser.STRUM, 0); }
		public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public StrumFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_strumFunction; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterStrumFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitStrumFunction(this);
		}
	}

	[RuleVersion(0)]
	public StrumFunctionContext strumFunction() {
		StrumFunctionContext _localctx = new StrumFunctionContext(_ctx, State);
		EnterRule(_localctx, 34, RULE_strumFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 169; Match(STRUM);
			State = 170; Match(LPAREN);
			State = 171; _localctx.offset = number();
			State = 172; Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TimesFunctionContext : ParserRuleContext {
		public IToken amount;
		public ITerminalNode TIMES() { return GetToken(HarmonyParser.TIMES, 0); }
		public ITerminalNode DECIMAL_LITERAL() { return GetToken(HarmonyParser.DECIMAL_LITERAL, 0); }
		public TimesFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_timesFunction; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterTimesFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitTimesFunction(this);
		}
	}

	[RuleVersion(0)]
	public TimesFunctionContext timesFunction() {
		TimesFunctionContext _localctx = new TimesFunctionContext(_ctx, State);
		EnterRule(_localctx, 36, RULE_timesFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 174; Match(TIMES);
			State = 175; Match(LPAREN);
			State = 176; _localctx.amount = Match(DECIMAL_LITERAL);
			State = 177; Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BassFunctionContext : ParserRuleContext {
		public ITerminalNode BASS() { return GetToken(HarmonyParser.BASS, 0); }
		public BassFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bassFunction; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterBassFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitBassFunction(this);
		}
	}

	[RuleVersion(0)]
	public BassFunctionContext bassFunction() {
		BassFunctionContext _localctx = new BassFunctionContext(_ctx, State);
		EnterRule(_localctx, 38, RULE_bassFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 179; Match(BASS);
			State = 180; Match(LPAREN);
			State = 181; Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AddFunctionContext : ParserRuleContext {
		public ITerminalNode ADD() { return GetToken(HarmonyParser.ADD, 0); }
		public NoteLiteralContext noteLiteral() {
			return GetRuleContext<NoteLiteralContext>(0);
		}
		public AddFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_addFunction; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterAddFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitAddFunction(this);
		}
	}

	[RuleVersion(0)]
	public AddFunctionContext addFunction() {
		AddFunctionContext _localctx = new AddFunctionContext(_ctx, State);
		EnterRule(_localctx, 40, RULE_addFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 183; Match(ADD);
			State = 184; Match(LPAREN);
			State = 185; noteLiteral();
			State = 186; Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NoteLiteralContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(HarmonyParser.IDENTIFIER, 0); }
		public NoteLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_noteLiteral; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterNoteLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitNoteLiteral(this);
		}
	}

	[RuleVersion(0)]
	public NoteLiteralContext noteLiteral() {
		NoteLiteralContext _localctx = new NoteLiteralContext(_ctx, State);
		EnterRule(_localctx, 42, RULE_noteLiteral);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ChordLiteralContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(HarmonyParser.IDENTIFIER, 0); }
		public ChordLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_chordLiteral; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterChordLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitChordLiteral(this);
		}
	}

	[RuleVersion(0)]
	public ChordLiteralContext chordLiteral() {
		ChordLiteralContext _localctx = new ChordLiteralContext(_ctx, State);
		EnterRule(_localctx, 44, RULE_chordLiteral);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 190; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		public ITerminalNode DECIMAL_LITERAL() { return GetToken(HarmonyParser.DECIMAL_LITERAL, 0); }
		public ITerminalNode FLOAT_LITERAL() { return GetToken(HarmonyParser.FLOAT_LITERAL, 0); }
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.EnterNumber(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHarmonyParserListener typedListener = listener as IHarmonyParserListener;
			if (typedListener != null) typedListener.ExitNumber(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(_ctx, State);
		EnterRule(_localctx, 46, RULE_number);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 192;
			_la = _input.La(1);
			if ( !(_la==DECIMAL_LITERAL || _la==FLOAT_LITERAL) ) {
			_errHandler.RecoverInline(this);
			} else {
				if (_input.La(1) == TokenConstants.Eof) {
					matchedEOF = true;
				}

				_errHandler.ReportMatch(this);
				Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public static readonly string _serializedATN =
		"\x3\xAF6F\x8320\x479D\xB75C\x4880\x1605\x191C\xAB37\x3%\xC5\x4\x2\t\x2"+
		"\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4\t\t"+
		"\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r\t\r\x4\xE\t\xE\x4\xF\t\xF\x4\x10\t"+
		"\x10\x4\x11\t\x11\x4\x12\t\x12\x4\x13\t\x13\x4\x14\t\x14\x4\x15\t\x15"+
		"\x4\x16\t\x16\x4\x17\t\x17\x4\x18\t\x18\x4\x19\t\x19\x3\x2\x3\x2\a\x2"+
		"\x35\n\x2\f\x2\xE\x2\x38\v\x2\x3\x2\x3\x2\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3"+
		"\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x4\x3\x4\x3\x4\x3\x4\x3"+
		"\x5\x3\x5\a\x5N\n\x5\f\x5\xE\x5Q\v\x5\x3\x5\x3\x5\x3\x6\x3\x6\x3\x6\x5"+
		"\x6X\n\x6\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x5\a`\n\a\x3\b\x3\b\x3\t\x3\t"+
		"\x3\t\x3\t\x3\t\x3\t\x3\t\x3\t\x3\n\x3\n\x3\n\x3\n\x3\n\x3\n\x3\n\x3\n"+
		"\x3\n\x3\n\x3\v\x3\v\x3\v\x3\v\x5\vz\n\v\x3\f\x3\f\x3\f\x3\f\a\f\x80\n"+
		"\f\f\f\xE\f\x83\v\f\x3\f\x3\f\x3\f\x3\f\x3\f\x3\f\x3\f\x3\r\x3\r\x3\r"+
		"\x3\xE\x3\xE\x3\xE\x5\xE\x92\n\xE\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF"+
		"\x3\xF\x5\xF\x9B\n\xF\x3\x10\x3\x10\x3\x10\x3\x10\x3\x10\x3\x11\x3\x11"+
		"\x3\x11\x3\x11\x3\x11\x3\x12\x3\x12\x3\x12\x3\x12\x3\x12\x3\x13\x3\x13"+
		"\x3\x13\x3\x13\x3\x13\x3\x14\x3\x14\x3\x14\x3\x14\x3\x14\x3\x15\x3\x15"+
		"\x3\x15\x3\x15\x3\x16\x3\x16\x3\x16\x3\x16\x3\x16\x3\x17\x3\x17\x3\x18"+
		"\x3\x18\x3\x19\x3\x19\x3\x19\x2\x2\x2\x1A\x2\x2\x4\x2\x6\x2\b\x2\n\x2"+
		"\f\x2\xE\x2\x10\x2\x12\x2\x14\x2\x16\x2\x18\x2\x1A\x2\x1C\x2\x1E\x2 \x2"+
		"\"\x2$\x2&\x2(\x2*\x2,\x2.\x2\x30\x2\x2\x4\x3\x2\x13\x14\x3\x2$%\xBD\x2"+
		"\x32\x3\x2\x2\x2\x4;\x3\x2\x2\x2\x6G\x3\x2\x2\x2\bK\x3\x2\x2\x2\nT\x3"+
		"\x2\x2\x2\f_\x3\x2\x2\x2\xE\x61\x3\x2\x2\x2\x10\x63\x3\x2\x2\x2\x12k\x3"+
		"\x2\x2\x2\x14y\x3\x2\x2\x2\x16{\x3\x2\x2\x2\x18\x8B\x3\x2\x2\x2\x1A\x8E"+
		"\x3\x2\x2\x2\x1C\x9A\x3\x2\x2\x2\x1E\x9C\x3\x2\x2\x2 \xA1\x3\x2\x2\x2"+
		"\"\xA6\x3\x2\x2\x2$\xAB\x3\x2\x2\x2&\xB0\x3\x2\x2\x2(\xB5\x3\x2\x2\x2"+
		"*\xB9\x3\x2\x2\x2,\xBE\x3\x2\x2\x2.\xC0\x3\x2\x2\x2\x30\xC2\x3\x2\x2\x2"+
		"\x32\x36\x5\x4\x3\x2\x33\x35\x5\x6\x4\x2\x34\x33\x3\x2\x2\x2\x35\x38\x3"+
		"\x2\x2\x2\x36\x34\x3\x2\x2\x2\x36\x37\x3\x2\x2\x2\x37\x39\x3\x2\x2\x2"+
		"\x38\x36\x3\x2\x2\x2\x39:\a\x2\x2\x3:\x3\x3\x2\x2\x2;<\a\x4\x2\x2<=\a"+
		"\x1C\x2\x2=>\a\"\x2\x2>?\x3\x2\x2\x2?@\a\x6\x2\x2@\x41\a\x1C\x2\x2\x41"+
		"\x42\a\"\x2\x2\x42\x43\x3\x2\x2\x2\x43\x44\a\x5\x2\x2\x44\x45\a\x1C\x2"+
		"\x2\x45\x46\a$\x2\x2\x46\x5\x3\x2\x2\x2GH\a\x3\x2\x2HI\a\"\x2\x2IJ\x5"+
		"\b\x5\x2J\a\x3\x2\x2\x2KO\a\x17\x2\x2LN\x5\n\x6\x2ML\x3\x2\x2\x2NQ\x3"+
		"\x2\x2\x2OM\x3\x2\x2\x2OP\x3\x2\x2\x2PR\x3\x2\x2\x2QO\x3\x2\x2\x2RS\a"+
		"\x18\x2\x2S\t\x3\x2\x2\x2TW\x5\f\a\x2UV\a\x1A\x2\x2VX\x5\x1A\xE\x2WU\x3"+
		"\x2\x2\x2WX\x3\x2\x2\x2X\v\x3\x2\x2\x2Y`\x5\x14\v\x2Z`\x5\x10\t\x2[`\x5"+
		"\x12\n\x2\\`\x5\xE\b\x2]`\x5\x16\f\x2^`\x5\x18\r\x2_Y\x3\x2\x2\x2_Z\x3"+
		"\x2\x2\x2_[\x3\x2\x2\x2_\\\x3\x2\x2\x2_]\x3\x2\x2\x2_^\x3\x2\x2\x2`\r"+
		"\x3\x2\x2\x2\x61\x62\a\"\x2\x2\x62\xF\x3\x2\x2\x2\x63\x64\a\a\x2\x2\x64"+
		"\x65\x5,\x17\x2\x65\x66\a\x15\x2\x2\x66g\x5\x30\x19\x2gh\a\x19\x2\x2h"+
		"i\x5\x30\x19\x2ij\a\x16\x2\x2j\x11\x3\x2\x2\x2kl\a\b\x2\x2lm\x5.\x18\x2"+
		"mn\a\x15\x2\x2no\x5\x30\x19\x2op\a\x19\x2\x2pq\x5\x30\x19\x2qr\a\x19\x2"+
		"\x2rs\a$\x2\x2st\a\x16\x2\x2t\x13\x3\x2\x2\x2uv\a\t\x2\x2vz\x5\n\x6\x2"+
		"wx\a\t\x2\x2xz\x5\x30\x19\x2yu\x3\x2\x2\x2yw\x3\x2\x2\x2z\x15\x3\x2\x2"+
		"\x2{\x81\a\n\x2\x2|}\x5,\x17\x2}~\a\x19\x2\x2~\x80\x3\x2\x2\x2\x7F|\x3"+
		"\x2\x2\x2\x80\x83\x3\x2\x2\x2\x81\x7F\x3\x2\x2\x2\x81\x82\x3\x2\x2\x2"+
		"\x82\x84\x3\x2\x2\x2\x83\x81\x3\x2\x2\x2\x84\x85\x5,\x17\x2\x85\x86\a"+
		"\x15\x2\x2\x86\x87\x5\x30\x19\x2\x87\x88\a\x19\x2\x2\x88\x89\x5\x30\x19"+
		"\x2\x89\x8A\a\x16\x2\x2\x8A\x17\x3\x2\x2\x2\x8B\x8C\a\v\x2\x2\x8C\x8D"+
		"\t\x2\x2\x2\x8D\x19\x3\x2\x2\x2\x8E\x91\x5\x1C\xF\x2\x8F\x90\a\x1A\x2"+
		"\x2\x90\x92\x5\x1A\xE\x2\x91\x8F\x3\x2\x2\x2\x91\x92\x3\x2\x2\x2\x92\x1B"+
		"\x3\x2\x2\x2\x93\x9B\x5 \x11\x2\x94\x9B\x5\x1E\x10\x2\x95\x9B\x5\"\x12"+
		"\x2\x96\x9B\x5$\x13\x2\x97\x9B\x5&\x14\x2\x98\x9B\x5(\x15\x2\x99\x9B\x5"+
		"*\x16\x2\x9A\x93\x3\x2\x2\x2\x9A\x94\x3\x2\x2\x2\x9A\x95\x3\x2\x2\x2\x9A"+
		"\x96\x3\x2\x2\x2\x9A\x97\x3\x2\x2\x2\x9A\x98\x3\x2\x2\x2\x9A\x99\x3\x2"+
		"\x2\x2\x9B\x1D\x3\x2\x2\x2\x9C\x9D\a\r\x2\x2\x9D\x9E\a\x15\x2\x2\x9E\x9F"+
		"\a$\x2\x2\x9F\xA0\a\x16\x2\x2\xA0\x1F\x3\x2\x2\x2\xA1\xA2\a\f\x2\x2\xA2"+
		"\xA3\a\x15\x2\x2\xA3\xA4\a$\x2\x2\xA4\xA5\a\x16\x2\x2\xA5!\x3\x2\x2\x2"+
		"\xA6\xA7\a\xF\x2\x2\xA7\xA8\a\x15\x2\x2\xA8\xA9\a\"\x2\x2\xA9\xAA\a\x16"+
		"\x2\x2\xAA#\x3\x2\x2\x2\xAB\xAC\a\xE\x2\x2\xAC\xAD\a\x15\x2\x2\xAD\xAE"+
		"\x5\x30\x19\x2\xAE\xAF\a\x16\x2\x2\xAF%\x3\x2\x2\x2\xB0\xB1\a\x10\x2\x2"+
		"\xB1\xB2\a\x15\x2\x2\xB2\xB3\a$\x2\x2\xB3\xB4\a\x16\x2\x2\xB4\'\x3\x2"+
		"\x2\x2\xB5\xB6\a\x11\x2\x2\xB6\xB7\a\x15\x2\x2\xB7\xB8\a\x16\x2\x2\xB8"+
		")\x3\x2\x2\x2\xB9\xBA\a\x12\x2\x2\xBA\xBB\a\x15\x2\x2\xBB\xBC\x5,\x17"+
		"\x2\xBC\xBD\a\x16\x2\x2\xBD+\x3\x2\x2\x2\xBE\xBF\a\"\x2\x2\xBF-\x3\x2"+
		"\x2\x2\xC0\xC1\a\"\x2\x2\xC1/\x3\x2\x2\x2\xC2\xC3\t\x3\x2\x2\xC3\x31\x3"+
		"\x2\x2\x2\n\x36OW_y\x81\x91\x9A";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
